acounts/api/urls.py
from django.urls import path
from acounts.api import views as api_views
from acounts.api.views import apicustomerlist,apilogin

#app_name = 'acounts'
urlpatterns = [
    path('', api_views.apiview, name='api'),
    path('customer/<str:pk>/', api_views.apicustomer, name='apicustomer'),
    path('customers/', apicustomerlist.as_view(), name='apicustomerlist'),
    path('update_customer/<str:pk>/', api_views.apicustomer_update, name='apicustomer_update'),
    path('delete_customer/<str:pk>/', api_views.apicustomer_delete, name='apicustomer_delete'),
    path('create_customer/', api_views.apicustomer_create, name='apicustomer_create'),

    path('register/', api_views.apiregister, name='apiregister'),
    path('user_detil/', api_views.apiuser_detil, name='apiuser_detil'),
    path('user_update/', api_views.apiuser_update, name='apiuser_update'),
    path('login/', apilogin.as_view(), name='apilogin'),

























    path('product/<str:pk>/', api_views.apipruduct, name='apiproduct'),
    path('order/<str:pk>/', api_views.apiorder, name='apiorder'),
    path('createorder/', api_views.apicreateorder, name='apicreateorder'),
    path('updateorder/<str:pk>/', api_views.apiupdateorder, name='apiupdateorder'),
    path('deleteorder/<str:pk>/', api_views.apideleteorder, name='apideleteorder'),



]

acounts/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from django.contrib.auth import views as auth_views

#app_name = 'acounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),


    path('user_page/', views.userpage, name='user_page'),

    path('products/',views.products, name='products'),
    path('create_product/',views.createproduct, name='create_product'),
    path('update_product/<str:id>/',views.updateproduct, name='update_product'),
    path('delete_product/<str:id>/',views.deleteproduct, name='delete_product'),
    
    path('customer/<str:id>/',views.customer, name='customer'),
    path('customers_page/',views.customerspage, name='customers_page'),
    path('create_customer/',views.createcustomer, name='create_customer'),
    path('update_customer/<str:id>/',views.updatecustomer, name='update_customer'),
    path('delete_customer/<str:id>/',views.deletecustomer, name='delete_customer'),
    
    path('create_order/<str:id>/',views.createorder, name='create_order'),
    path('update_order/<str:id>/',views.updateorder, name='update_order'),
    path('delete_order/<str:id>/',views.deleteorder, name='delete_order'),
    path('total_order/',views.totalorder, name='totalorder'),
    
    

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="acounts/password_reset.html"),name="reset_password"),

    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name="acounts/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="acounts/password_reset_form.html"), name="password_reset_confirm"),

    path('passowrd_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="acounts/password_reset_complete.html"), name="password_reset_complete"),

]


# reset password steps
'''
1 - Submit email form                         //PasswordResetView.as_view() 
2 - Email sent success message                //PasswordResetDoneView.as_view() 
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view() 
'''

crm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('acounts.urls')),

    # REST FRAMEWORK  API
    path('api/acounts/',include('acounts.api.urls'), name='acountsapi'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acounts/models.py

from django.db import models
from django.db.models.query_utils import select_related_descend
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

##############


class Customer(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    adress = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


################
class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Out Door', 'Out Door'),
    )
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=10000, decimal_places=2, null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.name


###############
class Order(models.Model):
    STATUS = (
        ('pending', 'pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered')
    )
    customer = models.ForeignKey(
        Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    note = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.product}({self.customer})"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_pic = models.ImageField(
        default='default.jpg', upload_to='profile_pic', null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

acounts/forms.py
from django.db.models import fields
from django.db.models.deletion import PROTECT
from django.forms import ModelForm
from .models import Order, Product, Customer, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserupdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','email']



class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'



class ProfileUdateForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['profile_pic']

acounts/api/views.py

from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework import serializers, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.views import APIView
from django.contrib.auth import authenticate

from .serializers import CustomerSerializers, OrderSerializers, ProductSerializers, RegisterSerializers, UserSerializers
from acounts.models import Customer, Product, Order, User


@api_view(['GET'])
def apiview(request):

    api_urls = {
        '/api/acounts/customer/pk/': 'customer detile',
        '/api/acounts/customers/': 'customers all detile',
        '/api/acounts/update_customer/pk/': 'update customer ',
        '/api/acounts/create_customer/': 'create customer ',
        '/api/acounts/delete_customer/pk/': 'delet ecustomer ',


        '/api/acounts/register/': 'register user',
        '/api/acounts/user_detil/': ' user detial',
        '/api/acounts/user_update/': ' user update ',
        '/api/acounts/login/': 'login user ',




        'api/acounts/product/pk': 'produduct detile',
        'api/acounts/order/pk': 'order detile',
        'api/createorder': 'create order',
        'api/updateorder/<str:pk>': 'update order ',
        'api/deleteorder/<str:pk>': 'delete order',
    }

    return Response(api_urls)


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
def apicustomer(request, pk):
    try:
        customer = Customer.objects.get(id=pk)
    except Customer.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if customer.user != user:
        return Response({'Error': 'you canot make premation '})

    if request.method == 'GET':

        serializers = CustomerSerializers(customer)
        return Response(serializers.data)


@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def apicustomer_create(request):
    getuser = request.user

    customer = Customer(user=getuser)

    if request.method == 'POST':
        serializers = CustomerSerializers(customer, data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
@permission_classes((IsAuthenticated,))
def apicustomer_update(request, pk):
    try:
        customer = Customer.objects.get(id=pk)
    except Customer.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if customer.user != user:
        return Response({'Error': 'you canot make premaion '})

    if request.method == 'PUT':
        data = {}
        serializers = CustomerSerializers(instance=customer, data=request.data)
        if serializers.is_valid():
            serializers.save()
            #data['success'] = "customer was UPdated"
            return Response(serializers.data)  # (data=data)

        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
@permission_classes((IsAuthenticated,))
def apicustomer_delete(request, pk):
    try:
        customer = Customer.objects.get(id=pk)
    except Customer.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if customer.user != user:
        return Response({'Error': 'you canot make premaiton'})

    if request.method == 'DELETE':
        opration = customer.delete()
        data = {}
        if opration:
            data['success'] = "customer was deleted"
        else:
            data['feild'] = "delete feild !!!!!!!!"
        return Response(data=data)


class apicustomerlist(ListAPIView):
    serializer_class = CustomerSerializers
    # http://127.0.0.1:7000/api/acounts/customers/?page=2
    pagination_class = PageNumberPagination
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    # http://127.0.0.1:7000/api/acounts/customers/?search=karam
    filter_backends = (SearchFilter, OrderingFilter)
    # http://127.0.0.1:7000/api/acounts/customers/?search=karam&ordering=-date_created

    search_fields = ('name', 'adress', 'user__username')

    def get_queryset(self):
        return Customer.objects.filter(user=self.request.user).order_by('-date_created')


class apilogin(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        data = {}
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            try:
                token = Token.objects.get(user=user)
            except Token.DoesNotExist:
                token = Token.objects.create(user=user)
            data['response'] = 'succcessfully authenticate'
            data['pk'] = user.pk
            data['username'] = username
            data['token'] = token.key

        else:
            data['response'] = 'Error'
            data['error message'] = 'invalid authenticate'
        return Response(data)


@api_view(['POST'])
def apiregister(request):

    if request.method == 'POST':
        serializers = RegisterSerializers(data=request.data)
        data = {}
        if serializers.is_valid():
            user = serializers.save()
            data['Responce'] = 'successfuly registerions new user'
            data['Username'] = user.username
            data['Email'] = user.email
            token = Token.objects.get(user=user).key
            data['Token'] = token
        else:
            data = serializers.errors
        return Response(data)


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
def apiuser_detil(request):

    try:
        user = request.user
    except User.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializers = UserSerializers(user)
        return Response(serializers.data)


@api_view(['PUT'])
@permission_classes((IsAuthenticated,))
def apiuser_update(request):

    try:
        user = request.user
    except User.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        serializers = UserSerializers(instance=user, data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def apipruduct(request, pk):
    try:
        product = Product.objects.get(id=pk)
    except Product.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':

        serializers = ProductSerializers(product)
        return Response(serializers.data)


@api_view(['GET'])
def apiorder(request, pk):
    try:
        order = Order.objects.get(id=pk)
    except Order.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':

        serializers = OrderSerializers(order)
        return Response(serializers.data)


@api_view(['POST'])
def apicreateorder(request):
    serializers = OrderSerializers(data=request.data)
    if serializers.is_valid():
        serializers.save()
    return Response(serializers.data)


@api_view(['POST'])
def apiupdateorder(request, pk):
    order = Order.objects.get(id=pk)
    serializers = OrderSerializers(instance=order, data=request.data)
    if serializers.is_valid():
        serializers.save()
    return Response(serializers.data)


@api_view(['DELETE'])
def apideleteorder(request, pk):
    order = Order.objects.get(id=pk)
    order.delete()
    return Response("deleted is TRUE")

acounts/templates/acounts/customer.html
{%  extends 'acounts/main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid px-4 ">
	<br>
	<div class="row ">
		<div class="col col-md">
			<div class="card bg-light text-dark mb-4">
				<div class="card-body">
					<h3 class="text-muted" >{{ customer.name }} Page</h3>
					<p><span class="fw-bold">Customer Name : </span>{{ customer.name }}</p>
					<p><span class="fw-bold">Email : </span>{{ customer.email }} </p>
					<p><span class="fw-bold">Phone : </span>{{ customer.phone }}</p>	
					<p><span class="fw-bold">Adress : </span>{{ customer.adress }}</p>
					<a class="btn btn-info  btn-sm  m-2" href="{% url 'update_customer' customer.id %}">Update Customer</a>
					<a class="btn btn-danger  btn-sm  m-2 " href="{% url 'delete_customer' customer.id %}">Delete Customer</a>
					
				</div>
			</div>
		</div>

	</div>
</div>


<main>
	<div class="container-fluid px-4">
		<h3 class="mt-4 text-muted">{{ customer.name }} Orders</h3>
		<div class="card mb-4">
			<div class="card-header">
				<i class="fas fa-table me-1"></i>
				DataTable Example
				<span class="text-secondary mx-3">Order today : {{ order_today.count}}</span> 
				<span class="text-secondary me-3">byed today :  {{ mony_today }} &#36;</span>
				<span class="text-secondary me-3">Total Order :  {{ total_order }}</span> 
				<span class="text-secondary me-5">Total byed : {{ mony_total }} &#36;</span> 
				<a class="btn btn-primary mr-sm-2 ms-md-5"  href="{% url 'create_order' customer.id %}">Create Order</a>
	
			</div>
			<div class="card-body">
				<table id="datatablesSimple">
					<thead>
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Date Orderd</th>
							<th>Note</th>
							<th>Product Price</th>
							<th>Status</th>
							<th>Update</th>
							<th>Remove</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Date Orderd</th>
							<th>Note</th>
							<th>Product Price</th>
							<th>Status</th>
							<th>Update</th>
							<th>Remove</th>
						</tr>
					</tfoot>
					<tbody>
						{% for order in orders %}
							<tr class="fst-italic">
								<td>{{order.product}}</td>
								<td>{{order.product.category}}</td>
								<td>{{order.date_created|date:"m/d/Y   h:i A"}}</td>
								<td>{{order.note}}</td>
								<td>{{ order.product.price }} <span class="text-success fw-bold">&#36;</span></td>
								{% if order.status == "pending" %}
									<td class="text-danger fw-bold">{{ order.status }} <i class="fa fa-clock-o" aria-hidden="true"></i></td>
								{% elif order.status == "Out for delivery" %}
									<td class="text-warning fw-bold">{{ order.status }} <i class="fa fa-car" aria-hidden="true"></i></td>
								{% else %}
									<td class="text-success fw-bold">{{ order.status }} <i class="fa fa-check" aria-hidden="true"></i></td>	
								{% endif %}
								<td><a class="btn btn-sm btn-info" href="{% url 'update_order' order.id %}">Update</a></td>
								<td><a class="btn btn-sm btn-danger" href="{% url 'delete_order' order.id %}">Delete</a></td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>


{% endblock %}

acounts/templates/acounts/customer_form.html
{%  extends 'acounts/main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<style>
    #messages{
			background-color: rgb(11, 116, 7);
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
</style>

<br>
<div class="row ">
	<div class="col-md-5 shadow-lg p-3 mb-5 bg-light rounded container r">
        <h5>{{ action }}</h5>
		<hr>
		<div class="card card-body">
            <form method="POST" action="">
                {% csrf_token %}
                <tr>
                    <td>
                    <select name="user" required id="id_user" hidden >

                        <option value="{{ user.id }}" selected>{{ user }}</option>

                  </select>
                    </td>
                </tr>
                {% for message in messages %}
				<p id="messages">{{ message }}</p>
			    {% endfor %}
                <div class="mb-3">
                    <label for="id_name" class="form-label fw-bold">Name</label>
                    <input value="{{ c_name }}" type="text" class="form-control" id="id_name" name="name">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label fw-bold">Email address</label>
                    <input value="{{ c_email }}" type="email" class="form-control" id="id_email" name="email" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="id_phone" class="form-label fw-bold">Phone</label>
                    <input value="{{ c_phone }}" type="text" class="form-control" id="id_phone" name="phone">
                </div>
                <div class="mb-3">
                    <label for="id_adress" class="form-label fw-bold">Aderess</label>
                    <input value="{{ c_adress }}"ype="text" class="form-control" id="id_adress" name="adress"> 
                </div>
                <button type="submit" class="btn btn-primary">{{ butoon }}</button>
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

acounts/templates/acounts/customers_page.html

{%  extends 'acounts/main.html' %}
{% load static %}
{% block content %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Customers</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                DataTable Example
                <a class="btn btn-outline-success " href="{% url 'create_customer' %}" type="submit">Create Customer</a>
            </div>
            <div class="card-body">
                <table class="table-striped " style="background-color: rgb(250, 255, 248);" id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Orders</th>
                            <th>Add In</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Orders</th>
                            <th>Add In</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for customer in customers %}
                            <tr class="fst-italic">
                                <td><a class="nav-link" href="{% url 'customer' customer.id %}">{{ customer.name }}</td>
                                <td>{{ customer.phone }}</td>
                                <td>{{ customer.email }} <span class="text-success fw-bold"></span></td>
                                <td>{{ customer.order_set.all.count }}</td>
                                <td>{{ customer.date_created|date:"m/d/Y   h:i A"}}</td>
                                <td><a class="btn btn-sm btn-info" href="{% url 'update_customer' customer.id %}">Update</a></td>
                                <td><a class="btn btn-sm btn-danger" href="{% url 'delete_customer' customer.id %}">Delete</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
<!------------------------------------->
<div class="container-fluid">
    <form method="get" class="d-flex form-inline my-2 my-lg-0">
      <a class="btn btn-outline-primary mr-sm-2" href="{% url 'create_customer' %}">Create customer</a>
      <input class="form-control me-2" type="search" placeholder="Customer Name" aria-label="Search" name="name">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <h3 class="text-muted" >Customers Page</h3>
  </div>

acounts/templates/acounts/delete_customer.html
{%  extends 'acounts/main.html' %}

{% load static %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <p>Are You Sure You Want To Delete The Customer "<span class="text-warning fw-bold">{{ customer.name }}</span>" ?</p>
            <table class="table table-sm">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Adress</th>
                    <th>Add in</th>
                </tr>
                <tr class="fst-italic">
                    <td>{{customer.name}}</td>
                    <td>{{customer.email}}</td>
                    <td>{{ customer.phone }} </td>
                    <td>{{ customer.adress }} </td>
                    <td>{{customer.date_created|date:"m/d/Y   h:i A"}}</td>
                </tr>
            </table>                    
                <form method="POST">
                    {% csrf_token %}
                    <input class="btn btn-info" type=button value="Cancel" onClick="window.history.back();return false;">
        
                    <input class="btn btn-danger" type="submit"  value="Delete">
                </form>
        </div>
    </div>
</div>


{% endblock %}

acounts/templates/acounts/delete_product.html
{%  extends 'acounts/main.html' %}

{% load static %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <p>Are You Sure You Want To Delete "<span class="text-warning fw-bold">{{ product.name }}</span>"From The products ?</p>
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Add In</th>
                </tr>
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.price }} $</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.date_created|date:"m/d/Y   h:i A"}}</td>
                </tr>
            </table>                    
                <form method="POST">
                    {% csrf_token %}
                    <input class="btn btn-info" type=button value="Cancel" onClick="window.history.back();return false;">
        
                    <button class="btn btn-danger" type="submit"  value="Delete">Delete</button>
                </form>
        </div>
    </div>
</div>



{% endblock %}

acounts/templates/acounts/order_form.html
{%  extends 'acounts/main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<form method="POST" action=""  class="container">
    <h2 class="text-muted">{{ action }}</h2>
    <br>
    {% csrf_token %}
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Customer</th>
                        <th>Product</th>
                        <th>Status</th>
                        <th>Note</th>
                    </tr>
                    <tr>
                        <td>
                            <select name="customer"  id="id_customer" class="form-select" aria-label="Default select example">
                                {% if customerin != None %}
                                    <option value="{{ customerin.id }}" selected>{{ customerin }}</option>
                                {% else %}
                                    <option value="" selected>-----</option>
                                {% endif %}
                                {% for cus in customers %}
                                {% if cus.id != customerin.id %}
                                    <option value="{{ cus.id }}">{{cus}}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                            <select name="product"  id="id_product" class="form-select" aria-label="Default select example">
                                {% if productin != None %}
                                    <option value="{{ productin.id }}" selected>{{ productin }}</option>
                                {% else %}
                                    <option value="" selected>-----</option>
                                {% endif %}
                                {% for prod in products %}
                                {% if prod.id != productin.id %}
                                    <option value="{{ prod.id }}">{{prod}}</option>
                                {% endif %}   
                                {% endfor %}
                            </select>
                        </td>
                        <td>{{ form.status }} </td>
                        <!-- <td>
                            <select name="status"  id="id_status" class="form-select" aria-label="Default select example">
                                {% if statusin != None %}
                                    <option value="{{ statusin.id }}" selected >{{ statusin }}</option>
                                {% else %}
                                    <option value="" selected>-----</option>
                                {% endif %}
                                {% for stat in statuses %}
                                {% if stat != statusin %}
                                    <option value="{{ stat }}">{{ stat }}</option>
                                {% endif %}   
                                {% endfor %}
                          
                          </select>
                        </td> -->
                        
                        <td><input value="{{ notin }}" class="form-control" type="text" placeholder="Note" aria-label="default input example" name="note" maxlength="50" id="id_note"></td>
                    </tr>
                </table>
                <br>  
            


                <button class="btn btn-outline-success" type="submit" name="save">{{ button }}</button>
                <br>
                <input class="btn btn-outline-danger" type=button value="Cancel" onClick="window.history.back();return false;">
            </div>
        </div>
    </div>              
</form>
    

  
{% endblock %}